#!/usr/bin/env python3
"""
Generate direct_flash.tcl for the Doom app using the same direct-register
flashing style as the root bin_to_direct_flash.py script.

Default input: ./build/doom.bin
Default output: ./direct_flash.tcl
"""
import re
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP_NAME = "doom"

FLASH_BASE = 0x08000000
PAGE_SIZE = 512
FLASH_KEY = 0x40022004
FLASH_STS = 0x4002200C
FLASH_CTRL = 0x40022010
FLASH_ADD = 0x40022014
IWDG_KEY = 0x40003000
IWDG_PREDIV = 0x40003004
IWDG_RELV = 0x40003008


def safe_tmp_name(path):
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", path.stem)
    return f"/tmp/{stem}_direct_verify.bin"


def tcl_quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if len(sys.argv) > 1:
    bin_path = Path(sys.argv[1])
    if not bin_path.is_absolute():
        bin_path = HERE / bin_path
else:
    bin_path = HERE / "build" / f"{APP_NAME}.bin"

out_path = HERE / "direct_flash.tcl"

if not bin_path.exists():
    print(f"ERROR: {bin_path} not found. Run ./build_doom.sh first.", file=sys.stderr)
    sys.exit(1)

raw = bin_path.read_bytes()
if not raw:
    print(f"ERROR: {bin_path} is empty.", file=sys.stderr)
    sys.exit(1)

padded = raw
if len(padded) % 4:
    padded += b"\xff" * (4 - (len(padded) % 4))

words = list(struct.unpack("<" + "I" * (len(padded) // 4), padded))
nbytes_raw = len(raw)
nbytes_padded = len(padded)
nwords = len(words)
npages = (nbytes_padded + PAGE_SIZE - 1) // PAGE_SIZE
pages = [FLASH_BASE + i * PAGE_SIZE for i in range(npages)]
dump_path = safe_tmp_name(bin_path)
w0 = words[0]
w200_idx = PAGE_SIZE // 4
w200 = words[w200_idx] if w200_idx < len(words) else 0xFFFFFFFF
last_addr = FLASH_BASE + (nwords - 1) * 4
last_word = words[-1]

lines = [
    "# direct_flash.tcl — generated by gen_direct_flash.py",
    f"# Input: {bin_path.name}",
    f"# Raw size: {nbytes_raw} bytes; padded size: {nbytes_padded} bytes; words: {nwords}",
    f"# Flash range: 0x{FLASH_BASE:08X} - 0x{FLASH_BASE + nbytes_padded - 1:08X}",
    f"# Erasing {npages} page(s) of {PAGE_SIZE} bytes each",
    "",
    "init",
    "adapter speed 1000",
    "",
    "proc kick_iwdg {} {",
    f"    mww 0x{IWDG_KEY:08X} 0x0000AAAA",
    "}",
    "",
    "proc wait_flash {label} {",
    "    # Wait for FLASH_STS.BUSY bit0 to clear. Keep kicking IWDG while waiting.",
    "    for {set i 0} {$i < 200} {incr i} {",
    f"        set sr [mrw 0x{FLASH_STS:08X}]",
    "        if {($sr & 0x1) == 0} {",
    "            return $sr",
    "        }",
    "        kick_iwdg",
    "        sleep 5",
    "    }",
    f"    set sr [mrw 0x{FLASH_STS:08X}]",
    "    puts \"WARNING: flash still busy after wait during $label, SR=0x[format %08X $sr]\"",
    "    return $sr",
    "}",
    "",
    "puts \"Halting target...\"",
    "catch {halt}",
    "sleep 20",
    "catch {halt}",
    "sleep 20",
    "catch {halt}",
    "sleep 30",
    "",
    "# Extend/refresh independent watchdog so flash writes have enough time.",
    "kick_iwdg",
    "sleep 5",
    f"mww 0x{IWDG_KEY:08X} 0x00005555",
    "sleep 2",
    f"mww 0x{IWDG_PREDIV:08X} 0x00000006",
    "sleep 2",
    f"mww 0x{IWDG_RELV:08X} 0x00000FFF",
    "sleep 2",
    "kick_iwdg",
    "sleep 5",
    "puts \"IWDG refreshed/extended\"",
    "",
    "# Unlock flash control register.",
    f"mww 0x{FLASH_KEY:08X} 0x45670123",
    f"mww 0x{FLASH_KEY:08X} 0xCDEF89AB",
    "sleep 5",
    "wait_flash unlock",
    "",
    "# Clear PGERR/WRPRTERR/EOP flags.",
    f"mww 0x{FLASH_STS:08X} 0x00000034",
    "sleep 2",
    f"set sr [mrw 0x{FLASH_STS:08X}]",
    f"set cr [mrw 0x{FLASH_CTRL:08X}]",
    "puts \"After unlock: SR=0x[format %08X $sr] CR=0x[format %08X $cr]\"",
    "",
    f"# Erase exactly the pages needed for {nbytes_padded} padded bytes.",
]

for pg in pages:
    lines += [
        "kick_iwdg",
        f"puts \"Erasing page 0x{pg:08X}...\"",
        f"mww 0x{FLASH_ADD:08X} 0x{pg:08X}",
        f"mww 0x{FLASH_CTRL:08X} 0x00000002",
        f"mww 0x{FLASH_CTRL:08X} 0x00000042",
        "sleep 30",
        "wait_flash erase",
        f"mww 0x{FLASH_CTRL:08X} 0x00000000",
        f"mww 0x{FLASH_STS:08X} 0x00000034",
        "",
    ]

lines += [
    f"set sr [mrw 0x{FLASH_STS:08X}]",
    "puts \"After erase: SR=0x[format %08X $sr]\"",
    f"set p0 [mrw 0x{FLASH_BASE:08X}]",
    "puts \"First word after erase: 0x[format %08X $p0] (expect 0xFFFFFFFF)\"",
    "",
    f"# Program {nwords} 32-bit words.",
    "kick_iwdg",
    f"mww 0x{FLASH_CTRL:08X} 0x00000001",
]

for i, word in enumerate(words):
    if i % 30 == 0:
        lines += [
            f"# IWDG kick at word {i}",
            "kick_iwdg",
        ]
    lines.append(f"mww 0x{FLASH_BASE + i * 4:08X} 0x{word:08X}")

lines += [
    "sleep 5",
    "wait_flash program",
    f"mww 0x{FLASH_CTRL:08X} 0x00000000",
    "",
    f"set sr [mrw 0x{FLASH_STS:08X}]",
    "puts \"Post-write SR=0x[format %08X $sr] (EOP bit without PGERR/WRPRTERR is good)\"",
    "",
    "# Quick verify a few words.",
    f"set f0 [mrw 0x{FLASH_BASE:08X}]",
    f"set f200 [mrw 0x{FLASH_BASE + 0x200:08X}]",
    f"set flast [mrw 0x{last_addr:08X}]",
    f"puts \"f0=0x[format %08X $f0] expect=0x{w0:08X}\"",
    f"puts \"f200=0x[format %08X $f200] expect=0x{w200:08X}\"",
    f"puts \"flast=0x[format %08X $flast] expect=0x{last_word:08X}\"",
    "",
    "# Full dump for Linux cmp verification.",
    f"dump_image {tcl_quote(dump_path)} 0x{FLASH_BASE:08X} {nbytes_raw}",
    "puts \"Dump done. Verify on Linux with:\"",
    f"puts \"  cmp build/{bin_path.name} {dump_path} && echo VERIFIED\"",
    "",
    "kick_iwdg",
    "puts \"Booting firmware...\"",
    "reset run",
]

out_path.write_text("\n".join(lines) + "\n")
print(f"Generated {out_path} ({len(lines)} lines, {nwords} words, {npages} pages)")
print(f"Expected f0=0x{w0:08X} f200=0x{w200:08X} flast=0x{last_word:08X}")
